//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PeripheralSmearInterp.Resource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PeripheralSmearInterp.Resource.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (none).
        /// </summary>
        internal static string access {
            get {
                return ResourceManager.GetString("access", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to class EHRdata {{
        ///  static patientName = &quot;{0}&quot;;
        ///  static last4 = &quot;{1}&quot;;
        ///  static age = {2};
        ///  static sex = &quot;{3}&quot;;
        ///  static reasonForConsult = &quot;{4}&quot;;
        ///
        ///{5}
        ///
        ///
        ///  static rpi() {{
        ///    if(!(EHRdata.ReticulocytesPct.result === null || EHRdata.hematocrit.result === null)){{
        ///      var maturationFactor = -1;
        ///      if(EHRdata.hematocrit.result &gt;= 35){{
        ///        maturationFactor = 1.0;
        ///      }} else if(EHRdata.hematocrit.result &gt;= 25){{
        ///        maturationFactor = 1.5;
        ///      }} else if(EHRdata.hematocrit.r [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string EHRDataJs {
            get {
                return ResourceManager.GetString("EHRDataJs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --labs
        ///drop table if exists #labExtract
        ///select p.patientsid, i.TestId, t.labchemtestname, o.topography Specimen, LabChemResultValue, Inequality
        ///	, case when i.TestId = 406485 /*Urine blood */ then Field1 else Number end Number
        ///	, c.reflow, c.refhigh, c.Units, labchemcompletedatetime SpecimenDate
        ///into #labExtract
        ///from [DOEx].[Chem_PatientLabChem_SPV_ColumnIndex] c
        ///join (select PatientSID from [Bashar].[Consult_List] where CPRSStatus = &apos;PENDING&apos;) p on p.patientsid = c.patientsid
        ///join dim.testid i on i [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Extraction_all {
            get {
                return ResourceManager.GetString("Extraction_all", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 425329	hematocrit
        ///459578	Eosinophils
        ///425336	MCV
        ///459522	WBCs
        ///413576	Neutrophils
        ///456225	Basophils
        ///454495	hemoglobin
        ///414555	Platelets
        ///465969	Lymphocytes
        ///415413	NeutrophilsAbs
        ///445101	MCH
        ///432484	RDW
        ///412980	RBCs
        ///483320	ImmatureGranulocytes
        ///483341	NucleatedRBCs
        ///449664	Monocytes
        ///405761	MeanPlateletVolume
        ///408720	MCHC
        ///409934	LymphocytesAbs
        ///430391	BilirubinTotal
        ///419662	BilirubinIndirect
        ///411231	Ferritin
        ///597383	Transferrin
        ///413565	Iron
        ///475787	B12
        ///597384	TransferrinSaturation
        ///412288	TIBC
        ///406485	 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TestIdToWebIdDictionary {
            get {
                return ResourceManager.GetString("TestIdToWebIdDictionary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MPV|BLOOD	405761
        ///URINE BLOOD|URINE	406485
        ///MCHC|BLOOD	408720
        ///ABSOLUTE LYMPHOCYTE COUNT|BLOOD	409934
        ///FERRITIN|SERUM	411231
        ///TIBC|SERUM	412288
        ///RBC|BLOOD	412980
        ///IRON|SERUM	413565
        ///NEUT %|BLOOD	413576
        ///PLT|BLOOD	414555
        ///RETICULOCYTES (%)|BLOOD	415265
        ///ABSOLUTE NEUTROPHIL COUNT|BLOOD	415413
        ///HAPTOGLOBIN (WROX)|SERUM	419447
        ///DIR. BILIRUBIN|SERUM	419662
        ///LDH|SERUM	419678
        ///HCT|BLOOD	425329
        ///MCV|BLOOD	425336
        ///TOT. BILIRUBIN|SERUM	430391
        ///RDW|BLOOD	432484
        ///HOMOCYSTEINE,SERUM|SERUM	433309
        ///TSH|SERUM	441981
        ///MCH|B [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TestNameSpecimenToTestId {
            get {
                return ResourceManager.GetString("TestNameSpecimenToTestId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --Remove old VISTA consults
        ///delete from Bashar.Consult_List where ConsultSID &lt; 100
        ///
        ///--Add new VISTA consults
        ///insert into Bashar.Consult_List
        ///select p.PatientName, v.Last4, p.Age, p.Gender, p.PatientSID, ConsultDate RequestDateTime, v.CPRSStatus,
        ///	row_number() over(partition by 1 order by v.LastName, v.FirstInitial, v.Last4) ConsultSID, null InpatOutpat, null ProvisionalDiagnosis, null ConsultReason
        ///from Bashar.Consult_List_FromVista v
        ///join cdwwork.spatient.spatient p on right(p.PatientSSN,4) = v.las [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string UpdateCDWFromVista {
            get {
                return ResourceManager.GetString("UpdateCDWFromVista", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (none).
        /// </summary>
        internal static string verify {
            get {
                return ResourceManager.GetString("verify", resourceCulture);
            }
        }
    }
}
